name: Test e Formattazione Winery

on: [push, pull_request]  # trigger, fa partire autom. il processo in 2 casi precisi

jobs:  # lavori da fare
  test:
    runs-on: ubuntu-latest # server virtuale con cui accede GitHub
    steps:  # passaggi 
    - name: Checkout del codice
      uses: actions/checkout@v4 # aggiornato da v3 a v4
      
    - name: Setup Python
      uses: actions/setup-python@v5 # aggiornato da v4 a v5
      with:
        python-version: '3.10'
        
    - name: Installa le dipendenze
      run: pip install -r requirements.txt
      
    - name: Controlla formattazione (Black)
      run: black --check src/ tests/
      
    - name: Esegui i Test (Pytest)
      run: pytest tests/